version: "3.9"
services:
  backend-api:
    container_name: backend-api
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    init: true
    ports:
      - "54321:54321"
    environment:
      - VERSION=1.0.0
      - REST_PORT=54321
      - GO_ENV=production
      - SWAGGER_HOST=localhost:54321
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=nanda
      - DB_PASS=nanda
      - DB_NAME=db
      - DB_SSLMODE=disable
      - TIMEZONE=Asia/Jakarta
    networks:
      - net-nanda
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=nanda
      - POSTGRES_PASSWORD=nanda
    ports:
      - "5432:5432"
    networks:
      - net-nanda
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
networks:
  net-nanda:
    driver: bridge
